---
- name: "build environment file"
  template:
    src: environment.j2
    dest: "{{ deploy_helper.new_release_path }}/environment"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0640
