---
- name: "install Python requirements into virtualenv"
  pip:
      chdir: "{{ deploy_helper.new_release_path }}"
      requirements: "requirements.txt"
      virtualenv: "{{ deploy_helper.new_release_path }}/env"
      virtualenv_site_packages: "{{ virtualenv_site_packages|default(true) }}"
